### PR TITLE
Fix pre-commit config

### PR DESCRIPTION
**Pull request by dmitryduev**
@mcoughlin let's fix it properly.

### CODE REVIEW

**Comment by AshishMahabal** [comment]
Please add top-label too - variable type

**Comment by dmitryduev** [comment]
@AshishMahabal sorry?

**Comment by AshishMahabal** [comment]
I responded to the wrong notification. There were two dozen 
notifications on PR 33, and then that first one on 34.
Sorry. I meant please add "top label" to the histogram.

**Comment by mcoughlin** [comment]
What does that mean @AshishMahabal ?

**Pull request merged**
