### PR TITLE
WIP: Enable nested ELS_ECE_EAOV period finding

### PR DESCRIPTION
**Pull request by bfhealy**
This PR refactors `periodsearch.py` to enable a nested ELS - ECE - EAOV approach on GPUs.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@bfhealy do you feel like we need it? Aren't we running all algorithms at full frequency grid now?

**Comment by bfhealy** [comment]
@mcoughlin I'm not completely sure -  we are indeed running each algorithm on the full frequency grid, but Matthew suggested we might improve our performance by nesting the algorithms. I thought I'd experiment using this PR and Expanse.

I think the primary means of improvement will be to expand the `freqs_to_remove` list in the script, e.g. with multiples of 1 year. I've found that for the known periodic sources, ~2/3 of ECE and EAOV periods from DR16 are within 10% of the period values in the golden set. Significantly fewer of the ELS periods (~7%) are within 10% of the golden set periods. I'll make sure to post an issue about this too.

**Comment by mcoughlin** [comment]
@bfhealy Ok as long as both separate and nested remain possible

**Comment by bfhealy** [comment]
Closing in favor of #358.

**Pull request closed without merging**
