### PR TITLE
Do not use Dropout for input features/dmdt's

### PR DESCRIPTION
**Pull request by dmitryduev**
Randomly dropping input feature/dmdt data is a bad idea and I'm not sure why I had it there in the first place. My guess is that the DNN performance will significantly improve once that is removed.

### CODE REVIEW

**Review by mcoughlin — APPROVED** [review]
Embarrassed to say that we should have realized the same on initial review ;)

**Comment by mcoughlin** [comment]
Do you understand the keras complaints @dmitryduev ?

**Comment by dmitryduev** [comment]
I'd guess that tf just lives a very intense life that we should all be envious about. Let's see if my hypothesis is correct.

**Comment by dmitryduev** [comment]
there you go @mcoughlin!

**Pull request merged**
